document.write(' <div class="footer"> ')
document.write(' <div class="container"> ')
document.write(' <div class="row footer-top"> ')
document.write(' <div class="col-md-4 padding-bottom-50">')
document.write(' <h4>ABOUT US</h4>')
document.write(' <p class="margin-bottom-20">The main motto of the Company is to promote the interest of its members to attain their social and economic betterment through self-help and mutual aid in accordance with co-operative principles. </p>')
document.write(' <a href="About.html" class="btn-sm btn-blue">Read More</a> </div>')
      
document.write(' <div class="col-md-4 padding-bottom-50">')
document.write(' <h4>OUR SCHEMES</h4>')
document.write(' <ul class="footer-list">')
document.write(' <li class="first"><a href="fd.html">Fixed Deposit Scheme</a></li>')
document.write(' <li><a href="rd.html">Recurring Deposit Scheme</a></li>')
document.write(' <li><a href="mis.html">Monthly Income Scheme</a></li>')
document.write(' <li><a href="yis.html">Yearly Income Scheme</a></li>')
document.write(' <li><a href="saving.html">Saving Account</a></li>')
document.write(' </ul>')
document.write(' </div>')
      
document.write(' <div class="col-md-4 padding-bottom-50">')
document.write(' <h4>CONTACT DETAILS</h4>')
document.write(' <p><strong>Aisa Finance Nidhi Limited</strong></p>')
document.write(' <p class="contact_info"><i class="icon icon-pin-map"></i> Dev Colony,Ward no 1,Nagla road,Faizganj Behta,Budaun(243632)</p>')
document.write(' <p class="contact_info"><i class="icon icon-email-envelope"></i> <a href="mailto:aisafinance23@gmail.com">aisafinance23@gmail.com</a></p>')
document.write(' <p class="contact_info"><i class="icon icon-call-phone"></i> +91-8009123789</p>')
document.write(' </div>')
document.write(' </div>')
    
document.write(' <div class="row"> ')
document.write(' <div class="footer-bottom">')
document.write(' <div class="col-md-5">        ')   
document.write(' <div class="copyright ">')
document.write(' <p>© 2023 Aisa Finance Nidhi Limited. All Right Reserved</a></p>')
document.write(' </div> ')         
document.write(' </div>')

document.write(' <div class="col-md-2 text-center"> <a href="#top-intro" class="scrool top-scroll"><i class="icon icon-angle-up"></i></a> </div>')
document.write(' <div class="col-md-5"> ')
          
document.write(' <ul class="footer_social">')
document.write(' <li> Follow Us: </li>')
document.write(' <li> <a href="#"> <i class="icon icon-twitter"></i> </a> </li>')
document.write(' <li> <a href="#"> <i class="icon icon-youtube"></i> </a> </li>')
document.write(' <li> <a href="#"> <i class="icon icon-facebook"></i> </a> </li>')
document.write(' <li> <a href="#"> <i class="icon icon-linkedin"></i> </a> </li>')
document.write(' <li> <a href="#"> <i class="icon icon-google-plus"></i> </a> </li>')
document.write(' </ul>   ')       
document.write(' </div>  ')      
document.write(' </div>  ')    
document.write(' </div>  ')  
document.write(' </div> ') 
document.write(' </div>')