<!--begin top-intro -->
document.write(' <div class="top-intro" id="top-intro">   ')
document.write(' <div class="container"> ')
document.write(' <div class="row"> ')
      
document.write(' <div class="col-sm-4 details-wrapper">         ')
document.write(' <ul class="header_social">')
document.write(' <li> <a href="#" class="twitter"> <i class="icon icon-twitter"></i> </a> </li>')
document.write(' <li> <a href="#" class="pinterest"> <i class="icon icon-google-plus"></i> </a> </li>')
document.write(' <li> <a href="#" class="facebook"> <i class="icon icon-facebook"></i> </a> </li>')
document.write(' <li> <a href="#" class="skype"> <i class="icon icon-linkedin"></i> </a> </li>')
document.write(' </ul>     ')   
document.write(' </div>')
      
document.write(' <div class="col-sm-8"> ')
document.write(' <ul class="header_contact pull-right">')
document.write(' <li><i class="icon icon-call-phone"></i> +91-8009123789</li>')
document.write(' </ul>  ')      
document.write(' </div> ')     
document.write(' </div>  ')  
document.write(' </div>  ')
document.write(' </div>')
<!--end top-intro --> 

<!--begin header -->
document.write(' <header class="header"> ')  
  <!-- begin navbar -->
document.write(' <div class="navbar yamm navbar-default ">  ')   
document.write(' <div class="container"> ')
document.write(' <div class="navbar-header">')
document.write(' <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>')
document.write(' <a href="index.html" class="navbar-brand brand scrool" id="logo"><img src="images/logo.png" style="width:260px; height:70px; max-width:260px;" title="Aisa Finance Nidhi Limited"></a> </div>')
       
document.write(' <div id="navbar-collapse-02" class="navbar-collapse collapse"> ')        
document.write(' <ul class="nav navbar-nav text-right">')
document.write(' <li><a href="index.html">HOME</a></li>')
document.write(' <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">About us</a>')
document.write(' <ul role="menu" class="dropdown-menu">')
document.write(' <li><a href="About.html">About Company</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="Legal.html"> Legal Documents</a></li>')
document.write(' </ul>')
document.write(' </li>')
document.write(' <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Our Schemes</a>')
document.write(' <ul role="menu" class="dropdown-menu">')
document.write(' <li><a href="fd.html"> Fixed Deposit Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="rd.html"> Recurring Deposit Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="dd.html"> Daily Deposit Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="wd.html"> Weekly Deposit Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="mis.html"> Monthly Income Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="yis.html"> Yearly Income Scheme</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="saving.html"> Saving Account</a></li>')
document.write(' <li class="divider"></li>')
document.write(' <li><a href="gullak.html"> Gullak Plan</a></li>')
document.write(' </ul>')
document.write(' </li>')
document.write(' <li><a href="Loans.html">Loans</a></li>')
document.write(' <li><a href="Branches.html">Branches</a></li>')
document.write(' <li><a href="Downloads.html">Downloads</a></li>')
document.write(' <li><a href="gallery.html">Gallery</a></li>')
document.write(' <li><a href="Contact.html" class="menu-last">Contact</a></li>')
/*document.write(' <li><a href="default.aspx" class="menu-last">Login</a></li>')*/
document.write(' <li class="dropdown hidden-nav-item"><a href="#" data-toggle="dropdown" class="dropdown-toggle">How to Reach Us</a>')
document.write(' <ul role="menu" class="dropdown-menu" style="margin-top:10px !important;">')
document.write(' <li><a tabindex="-1" href="#"><i class="fa fa-phone"></i> +91-8009123789</a></li>')
document.write(' <li><a tabindex="-1" href="#"><i class="fa fa-envelope"></i> aisafinance23@gmail.com</a></li>')
document.write(' <li><a tabindex="-1" href="#"><i class="fa fa-map-marker"></i> Dev Colony,Ward no 1,Nagla road,Faizganj Behta,Budaun(243632)</a></li>')
document.write(' </ul>')
document.write(' </li>')
document.write(' </ul>   ')     
document.write(' </div>  ')    
document.write(' </div>')
    
document.write(' </div>')
  
document.write(' </header>')
<!--end header --> 