document.write(' <div style="box-shadow: 0 0 4px #999; padding:10px;">')
document.write(' <h5>Our Schemes:</h5>')
document.write(' <ul class="tags">')
document.write(' <li><a href="fd.html" style="display:block"> Fixed Deposit Scheme</a></li>')
document.write(' <li><a href="rd.html" style="display:block"> Recurring Deposit Scheme</a></li>')
document.write(' <li><a href="dd.html" style="display:block"> Daily Deposit Scheme</a></li>')
document.write(' <li><a href="wd.html" style="display:block"> Weekly Deposit Scheme</a></li>')
document.write(' <li><a href="mis.html" style="display:block"> Monthly Income Scheme</a></li>')
document.write(' <li><a href="yis.html" style="display:block"> Yearly Income Scheme</a></li>')
document.write(' <li><a href="saving.html" style="display:block"> Saving Account</a></li>')
document.write(' <li><a href="gullak.html" style="display:block"> Gullak Plan</a></li>')
document.write(' </ul>')
document.write(' <img src="images/rd.jpg" style="width:100%; height:auto"> </div>')